title: SHARON .L AKINYI
email: sharonlavin01@gmail.com
description: >-
  Applied Computer Technology major, tech enthusiast, and creative entrepreneur.
  Showcasing my projects, experiments, and journey — from cybersecurity labs to innovative business ideas.
github_username: Lavin01
minimal_mistakes_skin: plum # Try: neon, sunrise, mint, dark, plum
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
permalink: /:categories/:title/
paginate: 5
paginate_path: /page:num/
timezone: Africa/Nairobi

include:
  - _pages

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name: Sharon
  avatar: "/assets/images/bio-photo.jpg"
  bio: "APT major and creative entrepreneur passionate about cybersecurity, technology, and turning ideas into impactful solutions."
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Lavin01"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/"

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Lavin01"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/"

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: splash
      author_profile: true
      header:
        overlay_color: "#000"
        overlay_filter: "0.4"
        overlay_image: /assets/images/header-bg.jpg
        actions:
          - label: "Homepage"
            url: "/"
          - label: "Projects"
            url: "/projects/"
          - label: "Laba"
            url: "/laba/"
          - label: "Resume"
            url: "/resume/"
          - label: "Contact"
            url: "/contact/"
